//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_CDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Feature = new HashSet<Feature>();
            this.Issue = new HashSet<Issue>();
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string VIN { get; set; }
        public string Color { get; set; }
        public int IdDealershipSalon { get; set; }
        public string ImagePath { get; set; }
        public bool IdSold { get; set; }
        public decimal Price { get; set; }
        public int HP { get; set; }
        public int IdCarType { get; set; }
        public int IdEngine { get; set; }
        public int IdGearbox { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feature> Feature { get; set; }
        public virtual CarType CarType { get; set; }
        public virtual DealershipSalon DealershipSalon { get; set; }
        public virtual Engine Engine { get; set; }
        public virtual Gearbox Gearbox { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> Issue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
