//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_CDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id_person { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Id_asp_net_users { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
